//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Closet
    {
        //Added Data Annotations for the names of some properties in this table
        [Display(Name ="Item #")]
        public int ClothingID { get; set; }

        [Display(Name ="Clothing Type")]
        public int ClothingTypeID { get; set; }

        public string Name { get; set; }
        public string Photo { get; set; }
        public string Color { get; set; }
        public string Season { get; set; }
        public string Occasion { get; set; }

        [Display(Name="Clothing Type")]
        public virtual ClothingType ClothingType { get; set; }
    }
}
