USE [master]
GO

/****** Object:  Database [WardrobeDB]    Script Date: 10/17/2016 11:12:08 PM ******/
CREATE DATABASE [WardrobeDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WardrobeDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\WardrobeDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WardrobeDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\WardrobeDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WardrobeDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WardrobeDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WardrobeDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WardrobeDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WardrobeDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WardrobeDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WardrobeDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [WardrobeDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WardrobeDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WardrobeDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WardrobeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WardrobeDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WardrobeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WardrobeDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WardrobeDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WardrobeDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WardrobeDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WardrobeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WardrobeDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WardrobeDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WardrobeDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WardrobeDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WardrobeDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WardrobeDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WardrobeDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WardrobeDB] SET  MULTI_USER 
GO

ALTER DATABASE [WardrobeDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WardrobeDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WardrobeDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WardrobeDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WardrobeDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WardrobeDB] SET  READ_WRITE 
GO

